all:
	pdflatex design-document.tex
	bibtex design-document
	pdflatex design-document.tex
	pdflatex design-document.tex
	pdflatex design-document.tex

clean:
	rm design-document.bbl design-document.blg design-document.log design-document.aux 
